site_name: AI-Driven Predictive Maintenance
site_description: Advanced research and implementation in predictive maintenance using AI & ML
site_author: Raja Muhammad Awais
site_url: https://rajamuhammadawais.github.io/ai_driven_predictive_maintenance/
repo_url: https://github.com/RajaMuhammadAwais/ai_driven_predictive_maintenance
edit_uri: ""
use_directory_urls: true
copyright: "Copyright © 2025 Raja Muhammad Awais"

theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.ico
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: default
      primary: indigo
      accent: cyan
    - scheme: slate
      primary: indigo
      accent: cyan

plugins:
  - search
  - sitemap:
      changefreq: daily
      priority: 0.5
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RajaMuhammadAwais
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/rajamuhammadawais

docs_dir: docs

nav:
  - 🏠 Overview:
      - Introduction: index.md
  - ⚙️ Modules:
      - Data Ingestion & Preprocessing: data_ingestion_module_documentation.md
      - Predictive Failure Detection Model: predictive_failure_detection_model_documentation.md
      - AI-Driven Root Cause Prediction Model: root_cause_prediction_model_documentation.md
  - 🔬 Research:
      - Predictive Auto-Tuning: Predictive Auto-Tuning Research.md
      - Dynamic Resource Allocation: research_dynamic_resource_allocation.md
      - Fault Tolerance (GRU & LSTM): research_predictive_failure_detection.md
      - Root Cause Prediction Research: root_cause_prediction_research.md
