site_name: AI-Driven Predictive Maintenance
site_url: https://rajamuhammadawais.github.io/ai_driven_predictive_maintenance/
repo_url: https://github.com/RajaMuhammadAwais/ai_driven_predictive_maintenance
edit_uri: ""
use_directory_urls: true

theme:
  name: material

docs_dir: docs

nav:
  - Data Ingestion and Preprocessing Module: data_ingestion_module_documentation.md
  - Predictive Failure Detection Model: predictive_failure_detection_model_documentation.md
  - Research:
      - Dynamic Resource Allocation: research_dynamic_resource_allocation.md
      - Evaluating Fault Tolerance: research_predictive_failure_detection.md
  - AI-Driven Root Cause Prediction Model: root_cause_prediction_model_documentation.md
  - Root Cause Prediction Research: root_cause_prediction_research.md
