name: AI Driven Predictive Maintenance CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        # Install project if pyproject.toml or setup.py exists
        if [ -f pyproject.toml ]; then pip install .; fi
        if [ -f setup.py ]; then pip install .; fi

    - name: Lint Python code
      run: |
        flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests
      run: |
        if [ -d tests ]; then pytest tests/ --cov=src --cov-report=term; else echo "No tests directory"; fi
